#!/usr/bin/env python3
"""
Generate the synthetic front-end fixture, `sample-data.json`.

    python3 dashboard/make_fixture.py            # rewrite sample-data.json
    python3 dashboard/make_fixture.py --week 12  # a different week
    python3 dashboard/make_fixture.py --check    # verify it is reproducible

WHY THIS EXISTS
---------------
The fixture is a full dashboard payload for a week that has not happened, so the
front end can be worked on out of season. It used to be a committed blob with no
recorded provenance, which caused two problems.

First, it was easy to read as a real observed snapshot. It carried a `generated`
date of 2026-09-03 alongside final results for games dated 13 September through
27 October, which is only coherent once you know it is invented.

Second, and worse, nothing tied its shape to `collect()`. The fixture carried a
`whatif` key that `collect()` did not produce, so the What If tab worked against
the mock and reported "No precomputed board" against every live build. A payload
the real builder cannot produce hides exactly the bugs a fixture is supposed to
catch, so this script derives the fixture FROM `collect()` and then plays a
season forward into it. Anything `collect()` stops emitting disappears here too.

The results are drawn from the ESPN win probabilities with a fixed seed, so the
file is reproducible: same seed, same fixture, byte for byte.
"""

from __future__ import annotations

import argparse
import json
import os
import random
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)
sys.path.insert(0, HERE)

OUTPUT = os.path.join(HERE, "sample-data.json")
SEED = 2026


def synthetic_season(year: int, week: int, seed: int = SEED) -> dict:
    """The live season file, played forward through `week` with a fixed seed."""
    from fep import season as season_mod

    season = season_mod.load(year)
    rng = random.Random(seed)
    games = len(season["games"])

    # The live season file is filled in as sheets arrive, so out of season some
    # competitors have no picks and no points guess yet. A fixture needs a full
    # roster, so the gaps are invented here -- from the same seeded generator,
    # which keeps the file reproducible.
    for name in season["roster"]:
        sheet = season["picks"].get(name) or []
        if len(sheet) != games:
            season["picks"][name] = [
                "W" if rng.random() < float(g["weight"]) else "L"
                for g in season["games"]
            ]
        if season["points_guess"].get(name) is None:
            season["points_guess"][name] = rng.randrange(370, 460)

    for game in season["games"]:
        if game["nfl_week"] > week:
            continue
        weight = game["weight"]
        # Roll the actual ESPN number, so the invented season is at least a
        # plausible draw from the model the dashboard is displaying.
        game["result"] = "W" if rng.random() < float(weight) else "L"
        # Eagles scoring, loosely: more when they win.
        base = 27 if game["result"] == "W" else 17
        game["points_for"] = max(0, int(rng.gauss(base, 6)))
        game["result_source"] = "synthetic"

    # Snapshots are what the sparklines, Heat Check and volatility read, so the
    # fixture needs one per week up to the one being built.
    season["snapshots"] = []
    for w in range(0, week + 1):
        board = season_mod.run(season, through_week=w)
        season["snapshots"].append({
            "week": w,
            "weighted": {n: round(board.weighted[n], 1) for n in board.order},
            "current_points": dict(board.current_points),
            "deciding": {k: round(v, 1) for k, v in board.deciding.items()},
            "remaining_outcomes": board.remaining_outcomes,
        })
    return season


def build_fixture(year: int = 2026, week: int = 7, seed: int = SEED) -> dict:
    """A payload with exactly the shape `collect()` produces."""
    import build as build_mod
    from fep import season as season_mod

    season = synthetic_season(year, week, seed)

    # collect() reads the season off disk, so hand it this one instead. Going
    # through collect() rather than assembling the payload here is the whole
    # point: the fixture cannot drift from the live contract.
    real_load = season_mod.load
    season_mod.load = lambda y: season
    try:
        data = build_mod.collect(year, week)
    finally:
        season_mod.load = real_load

    data["fixture"] = {
        "synthetic": True,
        "seed": seed,
        "note": ("Generated by dashboard/make_fixture.py. The results and scores "
                 "are invented, drawn from the real ESPN win probabilities with a "
                 "fixed seed. This is a future state of the {} season, not an "
                 "observed one.".format(year)),
    }
    return data


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--year", type=int, default=2026)
    parser.add_argument("--week", type=int, default=7)
    parser.add_argument("--seed", type=int, default=SEED)
    parser.add_argument("--out", default=OUTPUT)
    parser.add_argument("--check", action="store_true",
                        help="regenerate and compare, without writing")
    args = parser.parse_args()

    data = build_fixture(args.year, args.week, args.seed)
    payload = json.dumps(data, indent=1, sort_keys=True) + "\n"

    if args.check:
        with open(args.out) as fh:
            current = fh.read()
        if current == payload:
            print("{} is reproducible".format(os.path.relpath(args.out, ROOT)))
            return 0
        print("{} does NOT match a fresh generation. Rerun without --check."
              .format(os.path.relpath(args.out, ROOT)))
        return 1

    with open(args.out, "w") as fh:
        fh.write(payload)
    print("Wrote {} ({:.0f} KB) -- {} week {}, seed {}".format(
        os.path.relpath(args.out, ROOT), os.path.getsize(args.out) / 1024,
        args.year, args.week, args.seed))
    return 0


if __name__ == "__main__":
    sys.exit(main())
