// Regenerate scrollbar-preview.html from the constants in Scrollbar.tsx, so
// the preview is always the CSS the override actually ships.
//
//     node framer/build-preview.js
//
// The import stripping is anchored to the start of a line on purpose. Without
// the anchor it also matches "!important" inside the CSS and silently eats the
// word, which produced a preview whose rules all lost their priority while
// looking perfectly fine in the source.
const fs = require("fs");
const path = require("path");

const here = __dirname;
const src = fs.readFileSync(path.join(here, "Scrollbar.tsx"), "utf8");
const body = src
    .split("// ---- the dial")[1]
    .replace(/^[\s\S]*?-{10,}\n/, "")
    .split("/**\n * Find the element")[0]
    .replace(/^import[^\n]*\n/gm, "")
    .replace(/: string|: number/g, "");

const mod = {};
new Function("exports", body +
    "\nexports.rules=rules;exports.W=TRACK_WIDTH;exports.I=TRACK_INSET;" +
    "\nexports.T=TRACK_COLOR;exports.F=FILL_COLOR;" +
    "\nexports.DT=DEBUG_TRACK;exports.DF=DEBUG_FILL;")(mod);

// The preview is static HTML with no React, so it does what the hook does: work
// out the inset for each row's width up front.
const insetFor = (w) =>
    mod.W == null ? mod.I : Math.max(0, Math.round((w * (1 - mod.W)) / 2));
const ROW = 900;
mod.CSS = mod.rules("preview", mod.T, mod.F, insetFor(ROW));
mod.DEBUG = mod.rules("previewdbg", mod.DT, mod.DF, insetFor(ROW));

for (const [name, css] of [["CSS", mod.CSS], ["DEBUG", mod.DEBUG]]) {
    const missing = ["margin: 0 ", "!important", "background-clip"]
        .filter((t) => !css.includes(t));
    if (missing.length) {
        throw new Error(name + " lost: " + missing.join(", "));
    }
}

const cards = Array.from({ length: 14 }, (_, i) => `<div class=card>${i + 1}</div>`).join("");
fs.writeFileSync(path.join(here, "scrollbar-preview.html"), `<!doctype html>
<meta charset=utf-8><title>FEP scrollbar</title>
<!-- Generated by framer/build-preview.js from framer/Scrollbar.tsx.
     Edit the constants there, then re-run it. -->
<style>
body{margin:0;background:#062b28;font-family:system-ui;color:#cfe;padding:34px 40px}
h3{font:700 13px system-ui;letter-spacing:.08em;margin:0 0 4px;color:#8ecfc6}
p{font:12px system-ui;color:#6d9a94;margin:0 0 12px}
.row{display:flex;gap:12px;overflow-x:scroll;padding-bottom:16px;width:900px}
.card{flex:none;width:150px;height:150px;border-radius:14px;display:grid;place-items:center;
  font:700 22px system-ui;color:#2c6b62;background:linear-gradient(160deg,#0e3f3a,#0a302c);
  border:1px solid #ffffff14}
.mark{position:absolute;top:0;bottom:0;width:1px;background:#ff5c5c;opacity:.8}
.wrap{position:relative}
${mod.CSS}
${mod.DEBUG}
</style>
<h3>STYLED</h3><p>Row ${ROW}px wide. Bar is ${mod.W == null ? "a fixed " + mod.I + "px inset" : Math.round(mod.W*100) + "% of the row"}, so the inset is ${insetFor(ROW)}px. Red lines mark it.</p>
<div class="wrap"><div class="row" data-fep-bar="preview">${cards}</div>
  <div class="mark" style="left:${insetFor(ROW)}px"></div>
  <div class="mark" style="right:${insetFor(ROW)}px"></div></div>
<h3 style="margin-top:26px">DEBUG COLOURS</h3><p>Same geometry, red track and cyan fill.</p>
<div class="wrap"><div class="row" data-fep-bar="previewdbg">${cards}</div>
  <div class="mark" style="left:${insetFor(ROW)}px"></div>
  <div class="mark" style="right:${insetFor(ROW)}px"></div></div>
<h3 style="margin-top:26px">DEFAULT</h3><p>What Chrome draws unaided.</p>
<div class="row">${cards}</div>`);
console.log("scrollbar-preview.html rebuilt, !important intact");
